### ISSUE TITLE
filter eav attribute in related field?

### ISSUE THREAD

**Issue by fcoppey** [jazzband/django-eav2#64]
when I try to filter a classifier that has a measure with an eav attribute like below:
Classifier.objects.filter(measure__eav__through_packaging=False)

I get the following error:
django.core.exceptions.FieldError: Related Field got invalid lookup: eav

is it normal?

**Comment by Dresdn** [comment]
I know this is way late, but still may help you or someone else. Since `eav` is added dynamically through the `Registry`, Django isn't aware of the `measure__eav` relationship.

To filter off an EAV, assuming your `models.Classifier` is *not* registered and `models.Measure` is registered through `eav.register()`, and there's a FK relationship `Classifer.measure`

```
qs = Measure.objects.filter(eav__through_packaging=False)
Classifier.objects.filter(measure__in=qs)
```
